In [36]:
#import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'#减少输出的信息


import tensorflow as tf

with tf.Session() as sess:
    #x = tf.ones([3,2],tf.int32)
    #print(sess.run(x))
    
    #b = [[1,2,3],[4,5,6]]
    #x = tf.ones_like(b)#构建一个形状和b一样的全为1的矩阵,还有zeros
    #print(sess.run(x))
    
    #x = tf.fill([2,3],2)
    #print(sess.run(x))
    
    #x = [1,2,3]
    #s = tf.shape(x)
    #print(sess.run(s))
    
    #x = [1,2,3]
    #y = tf.expand_dims(x,1)#提升维度的方向，此时可以为0或1
    #print(sess.run(y))
    
    #x = tf.linspace(1.0,5.0,5)#形成等差数列 (起点，终点，个数，名称可不写)
    #x = tf.range(1,13,1)#形成等差数列 (起点，终点，步长)
    #print(sess.run(x))
    
    x = tf.range(1,13,1)
    x = tf.reshape(x,[3,4])
    x = tf.reshape(x,[-1])
    x = tf.reshape(x,[-1,4])#最多只能有一维是-1，和numpy一样
    print(sess.run(x))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
